front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_client:
    path: /client
    defaults: { _controller: FrontBundle:Client:index}

front_satisfaction:
    path: /satisfaction
    defaults: { _controller: FrontBundle:Satisfaction:index }

front_distributeur:
    path: /distributeurs
    defaults: { _controller: FrontBundle:Distributeur:index }

front_country_ajax:
    path: /distributeurs/ajax/pays
    defaults: { _controller: FrontBundle:Distributeur:ajaxRefreshCountry}

front_departement_ajax:
    path: /distributeurs/ajax/departement
    defaults: { _controller: FrontBundle:Distributeur:ajaxRefreshDepartement}

front_ville_ajax:
    path: /distributeurs/ajax/ville
    defaults: { _controller: FrontBundle:Distributeur:ajaxRefreshVille}
