security:
    encoders:
        CoreBundle\Entity\User: bcrypt


    providers:
        our_db_provider:
            entity:
                class: CoreBundle:User

    firewalls:
        main:
            pattern:    /
            provider: our_db_provider
            form_login:
                login_path: front_user_login
                check_path: front_user_login_check
                default_target_path: front_homepage
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER}
