security:
    encoders:
        CoreBundle\Entity\User: bcrypt
        CoreBundle\Entity\Admin: bcrypt


    providers:
        userProvider:
            entity:
                class: CoreBundle:User
        adminProvider:
            entity:
                class: CoreBundle:Admin

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/admin
            provider: adminProvider
            form_login:
                login_path: back_admin_login
                check_path: back_admin_login_check
                default_target_path: back_homepage
            logout: true
            anonymous: true




    access_control:
        - { path: ^/admin$, roles: IS_AUTHENTICATED_FULLY }
