back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Dashboard:index }

back_layout:
    path:     /layout
    defaults: { _controller: BackBundle:Dashboard:layout }

back_admin_login:
    path:     /login
    defaults: { _controller: BackBundle:Admin:login }

back_admin_login_check:
    path:     /login_check

back_admin_logout:
    path:     /logout

back_user:
    prefix: /utilisateur
    resource: user.yml

back_admin:
    prefix: /administrateur
    resource: admin.yml

back_group:
    prefix: /group
    resource: group.yml

back_parameter:
    prefix: /parametre
    resource: parameter.yml

back_client:
    prefix: /clients
    resource: client.yml

back_pays:
    prefix: /pays
    resource: pays.yml

back_departement:
    prefix: /departements
    resource: departement.yml

back_ville:
    prefix: /villes
    resource: ville.yml

back_reference:
    prefix: /distributeurs
    resource: reference.yml