<?php

namespace CoreBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountry($countryId){
        return $this->createQueryBuilder('c')
            ->join('c.villes', 'v')
            ->join('v.country','co')
            ->where('c.id = :id')
            ->setParameter('id', $countryId)
            ->getQuery()->getResult();
    }

    public function findByDepartement($departementId){
        return $this->createQueryBuilder('c')
            ->join('c.villes', 'v')
            ->join('v.departement','de')
            ->where('de.id = :id')
            ->setParameter('id', $departementId)
            ->getQuery()->getResult();
    }

    public function findByVille($villeId){
        return $this->createQueryBuilder('c')
            ->join('c.villes', 'v')
            ->where('c.id = :id')
            ->setParameter('id', $villeId)
            ->getQuery()->getResult();
    }
}
