<?php

namespace CoreBundle\Repository;

/**
 * QuestionAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
