<?php

namespace CoreBundle\Repository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountry($countryId){
        return $this->createQueryBuilder('r')
            ->join('r.ville', 'v')
            ->join('v.country', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $countryId)
            ->getQuery()->getResult();
    }

    public function findByDepartement($departementId){
        return $this->createQueryBuilder('r')
            ->join('r.ville', 'v')
            ->join('v.departement', 'de')
            ->where('de.id = :id')
            ->setParameter('id', $departementId)
            ->getQuery()->getResult();
    }

    public function findByVille($villeId){
        return $this->createQueryBuilder('r')
            ->join('r.ville', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $villeId)
            ->getQuery()->getResult();
    }

}
